### ISSUE TITLE
websocket closed

### ISSUE THREAD

**Issue by Alzabel999999** [mdn522/binaryapi#18]
Hello again) I need to get candles by 24 currency. Sometime my script stopped,in logging i get websocket closed. Do you have there a method to check connect and reconnect?

**Comment by mdn522** [comment]
I have added a new example script named `auto_reconnect.py` in the `/examples` folder. have a look into that script to get ideas

Notes:
- If you subscribe to streams when you connect to the Binary websocket server. you need to move those codes into `on_connect()` function in the script `auto_reconnect.py`. because whenever the server reconnects you will lose all your previous subscriptions with the server. you have to subscribe again to any streams you need. `on_connect()` function will be called whenever server connects/reconnects
- The script is not heavily tested and may contain unseen bugs. use at caution and please report bugs if you find any

**Comment by mdn522** [comment]
You also need to update the library

**Comment by Alzabel999999** [comment]
Ok,Ill try this. Thanks. Also
I am have a 26 currency. By cycle I call a method to get candle and in callback function get data. But than websocket close. In scrypt I reconnect by methd connec() and have:

DEBUG:binaryapi.ws.client:{"echo_req":{"balance":1,"req_id":2,"subscribe":1},"error":{"code":"AuthorizationRequired","message":"Please log in."},"msg_type":"balance","req_id":2}
DEBUG:binaryapi.ws.client:{"echo_req":{"req_id":3,"subscribe":1,"transaction":1},"error":{"code":"AuthorizationRequired","message":"Please log in."},"msg_type":"transaction","req_id":3}

**Comment by mdn522** [comment]
Thanks for the report. there was an issue with the `connect()` function whenever called more than one time with the same API instance. I tried to fix it and now it should work as intended.

**You need to update the library again**

**Comment by Alzabel999999** [comment]
i will try and write then,thanks

**Comment by Alzabel999999** [comment]
HI, I updated library and start at the host. Now all my log full of :

ERROR:root:**error** reconnect() too many time please look log file

At the start i use binary.connect() and than by cycle use method to get candles. And by your  method in the other thread work functions from the auto_reconnect.py

**Comment by Alzabel999999** [comment]
What about ssl?

**Comment by mdn522** [comment]
You don't have to call `binary.connect()` at the start because you create `Binary()` instance. it automatically calls `connect()`. beside may I have a look into your code if it's not confidential.

**Comment by Alzabel999999** [comment]
Ok, Ill try this
